version : '3.*'
services :
  app:
    container_name : 'restapiMusikKorea'
    build : 
      context : .
      dockerfile : src/config/docker/Dockerfile
    ports :
      - 80:4000
    stdin_open : true
    depends_on:
      - database
    env_file:
      - .env
    volumes :
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  database:
    image : mysql
    ports:
      - ${db_port}:3306 
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_database}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image : phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_USERNAME: ${db_user}
      MYSQL_PASSWORD: ${db_password}

volumes : 
  db_data:
  node_modules:

